environment:
  matrix:
    - PYTHON_VERSION: "2.7"

platform:
  - x64

matrix:
  fast_finish: false

install:
  - set PATH=C:\Miniconda\Scripts
  - ps: If ($env:Platform -Match "x64") {$env:PATH="C:\Miniconda-x64\Scripts"}
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q --name python%PYTHON_VERSION% python=%PYTHON_VERSION% 
  - activate python%PYTHON_VERSION%
  - pip install --disable-pip-version-check --user --upgrade pip
  - pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy
  - conda install -q --name python%PYTHON_VERSION% setuptools numpy wheel cython
  - pip install -q pyinstrument
  - cython.exe itzi/swmm/swmm_c.pyx itzi/flow.pyx
  - python.exe setup.py build --compiler=mingw32
  - python.exe setup.py install

build: off

#~ test_script:
  #~ - nosetests

after_test:
  - python.exe setup.py bdist_wheel bdist_wininst

artifacts:
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
