# automate the pypi distribution process
image: ubuntu:16.10

pipelines:
  custom:  # done manually
    push_to_pypi:
      - step:
          script:
            - apt-get update
            - apt-get -y install python-numpy
            - pip install --disable-pip-version-check --upgrade pip
            - pip install pyinstrument
            - pip install twine
            - pip python setup.py sdist
            - twine -u $PYPI_USER -p $PYPI_PWD dist/*

