# automate the pypi distribution process
image: ubuntu:16.10

pipelines:
  custom:  # done manually
    push_to_pypi:
      - step:
          script:
            - apt-get update
            - apt-get -y install python-numpy python-pip
            - pip install --disable-pip-version-check --upgrade pip
            - pip install pyinstrument twine
            - python setup.py sdist
            - twine upload -u $PYPI_USER -p $PYPI_PWD dist/*

