# automate the pypi distribution process
image: ubuntu:16.10

pipelines:
  tags:
    '*':  # independent of tag name
      - step:
        script:
          - apt-get install numpy
          - pip install --disable-pip-version-check --upgrade pip
          - pip install pyinstrument
          - pip install twine
          - pip python setup.py sdist
          - twine -u $PYPI_USER -p $PYPI_PWD dist/*

