image: ubuntu:17.04

pipelines:
  default:
    - step:
        name: install and test with pylint
        script:
          - apt-get update
          - apt-get -y install pylint python-numpy python-pip cython
          - pip install --disable-pip-version-check --upgrade pip
          - pip install pyinstrument
          - cython itzi/swmm/swmm_c.pyx itzi/flow.pyx
          - pip install .
          - pylint itzi --extension-pkg-whitelist=numpy,itzi.flow,itzi.swmm.swmm_c > pylint_results.txt

  custom:  # done manually
    push_to_pypi:
      - step:
          name: automate the pypi distribution process
          script:
            - apt-get update
            - apt-get -y install python-numpy python-pip cython
            - pip install --disable-pip-version-check --upgrade pip
            - pip install pyinstrument twine
            - cython itzi/swmm/swmm_c.pyx itzi/flow.pyx
            - python setup.py sdist
            - twine upload -u $PYPI_USER -p $PYPI_PWD dist/*

